### ISSUE TITLE
How to render about page with the theme

### ISSUE THREAD

**Issue by tsai-jimmy** [ppoffice/hexo-theme-icarus#537]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by tsai-jimmy** [comment]
I found!
https://github.com/ppoffice/hexo-theme-icarus/pull/61

**Comment by Icecream-blue-sky** [comment]
> I found!
> #61
I have the same problem as you.But I can't understand what #61 mean.Is this?
1. Rename `themes\icarus\_config.yml.example` to `themes\icarus\_config.yml`;
2. Copy `themes\icarus\_config.yml.site.example` to your hexo blog's root directory and rename it to `_config.yml`;
3. Copy `themes\icarus\_source\*` into your hexo blog's directory `source`;
4. Then modify `theme` setting in `_config.yml` to `icarus`.
However, I can only do 3 and 4 step since I can't find _config.yml.example and _config.yml.site.example in my directory.So I'm confusing about how to solve the 404 problem of about page.Can you help me? Thks!
My hexo version is 3.9.0 with the latest version of icarus.
